var sites = [
  'http://www.crowdint.com',
  'http://ci.crowdint.com',
  'http://www.magmarails.com',
  'http://www.flickr.com/search/show/?q=granada&mt=photos&adv=1',
  'http://search.twitter.com/search?q=ruby+rails',
  'http://www.time.is',
  'http://search.twitter.com/search?q=crowdint',
  'https://rubygems.org/gems/rails3-jquery-autocomplete/stats',
  'http://192.168.1.120:3000',
  'http://www.angelguardian.com.mx',
  'http://www.flickr.com/search/show/?q=modern+architecture&mt=photos&adv=1',
  'http://mediotiempo.com',
  'http://www.macrumors.com',
  'http://www.flickr.com/search/show/?q=motivational&s=rec',
  'http://news.ycombinator.com/',
  'http://search.twitter.com/search?q=magmarails',
  'http://www.flickr.com/search/show/?q=white+sands&ct=0&mt=photos&adv=1'
];
